[package]
name = "isö8601"
version = "0.1.0"
authors = ["Robin Stumm <serverkorken@gmail.com>"]

[features]
chrono-serde = ["chrono/serde", "serde"]

[dependencies]
nom = "~4.0.0"
chrono = { version = "~0.4.6", optional = true }
serde = { version = "~1.0.76", optional = true }
